// Generated by IcedCoffeeScript 108.0.9
(function() {
  var assets, gameHeight, gameWidth, images, r;

  gameHeight = 1080;

  gameWidth = 2000;

  r = function(f) {
    return '/Resources/' + f;
  };

  images = {
    board: r('chessboard.jpg')
  };

  assets = {
    images: [images.board]
  };

  $(function() {
    Crafty.init(gameWidth, gameHeight, $('#game')[0]);
    return Crafty.scene('loading');
  });

  Crafty.scene('loading', function() {
    return Crafty.load(assets, function() {
      Crafty.e('2D, DOM, Text').text('LOADING....');
      return Crafty.scene('main');
    });
  }, function(e) {
    return {};
  }, function(e) {
    debugger;
  });

  Crafty.scene('main', function() {
    return Crafty.e('2D, DOM, Image').image(images.board);
  });

}).call(this);
