// Generated by IcedCoffeeScript 108.0.9
(function() {
  var Piece;

  window.ScoutChess = function() {
    var createTeamPieces, piece, _i, _j, _len, _len1, _ref, _ref1;
    this.pieces = [];
    createTeamPieces = function(team, isRightPlayer) {
      var b, pieces, r, s;
      s = function(fromLeft) {
        if (isRightPlayer) {
          return 7 - fromLeft;
        } else {
          return fromLeft;
        }
      };
      pieces = (function() {
        var _i, _results;
        _results = [];
        for (r = _i = 0; _i < 8; r = ++_i) {
          _results.push(new Piece(team, 'pawn', s(1), r));
        }
        return _results;
      })();
      b = function(rank, row) {
        return pieces.push(new Piece(team, rank, s(0), row));
      };
      b('rook', 0);
      b('knight', 1);
      b('bishop', 2);
      b('queen', 3);
      b('king', 4);
      b('bishop', 5);
      b('knight', 6);
      b('rook', 7);
      return pieces;
    };
    _ref = createTeamPieces('brown');
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      piece = _ref[_i];
      this.pieces.push(piece);
    }
    _ref1 = createTeamPieces('pink', true);
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      piece = _ref1[_j];
      this.pieces.push(piece);
    }
    return this;
  };

  Piece = function(team, rank, column, row) {
    this.team = team;
    this.rank = rank;
    this.column = ko.observable(column);
    this.row = ko.observable(row);
    return this;
  };

}).call(this);
